body { 
        font-family:arial;
     }
p{
  position:relative;
  top : 10px;
  right: 10px;
  height:150px;
  width:325px;
  border:2px solid black;
  padding:11px;
  display:inline-block;
  margin:30px;
  margin-left: 37px;
  background-color:#dedede;
  border-radius: 2px 2px;
}
b
{
  font-family: sans-serif;
  text-align: center;
  color:black;
  height:20px;
  width:100px;
  border:2px solid black;
  position:absolute;
  top:0.1px;
  right:0.1px;
}
@media(min-width:0px) and  (max-width:767px)
{
  p{
    width:inherit;
  }
}
@media(min-width:768px) and (max-width:991px)
{
  .hypo{
    width:inherit;
  }
}
@media(min-width:992px)
{
  body{
    display:inline-block;
    width:inherit;
  }
}
.hp
{
  background-color: #fc9fb6;
}
.hc
{
  background-color: #d10404;
  color:white;
}
.hk
{
  background-color: #f0e9c0;
}
